/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrawJPanel.java
 *
 * Created on 10-jan-2011, 14:23:10
 */

package nl.maes.bollenweddingapp;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;


/**
 *
 * @author lars
 */
public class DrawJPanel extends javax.swing.JPanel implements MouseListener, MouseMotionListener {

    private int lastX = 0;
    private int lastY = 0;
    BufferedImage image = null;

    /** Creates new form DrawJPanel */
    public DrawJPanel() {
        initComponents();
        this.addMouseListener(this);
        this.addMouseMotionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(512, 50));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetXY(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void resetXY(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetXY
       lastX = 0;
       lastY = 0;
    }//GEN-LAST:event_resetXY

     @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;  // Downcast to Graphics2D

        //... One time initialization of in-memory, saved image.
        if (image == null) {
            //... This is the first time, initialize _bufImage
            int w = this.getWidth();
            int h = this.getHeight();
            image = (BufferedImage) this.createImage(w, h);
            Graphics2D gc = image.createGraphics();
            gc.setColor(Color.WHITE);
            gc.fillRect(0, 0, w, h); // fill in background
        }

        //... Display the saved image.
        g2.drawImage(image, null, 0, 0);
        //drawCurrentShape(g2);


    }

    public void mouseClicked(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void mouseDragged(MouseEvent e) {
         if (lastX == 0) {
            lastX = e.getX();
        }
        if (lastY == 0) {
            lastY = e.getY();
        }
        Graphics2D g2 = (Graphics2D) image.getGraphics();
        g2.setStroke(new BasicStroke(2.0f));
        g2.draw(new Line2D.Double(lastX, lastY, e.getX(), e.getY()));
        lastX = e.getX();
        lastY = e.getY();

        this.repaint();
        

    }

    public void mouseMoved(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void saveImage() {
        try {
            ImageIO.write(image, "BMP", new File("image.bmp"));
        } catch (IOException ex) {
            Logger.getLogger(DrawJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
