/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 10-jan-2011, 20:29:28
 */

package nl.maes.bollenweddingapp;

import java.awt.Dimension;
import java.awt.Insets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.apache.commons.io.monitor.FileAlterationMonitor;
import org.apache.commons.io.monitor.FileAlterationObserver;


/**
 *
 * @author lars
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        BackgroundPanel bPanel = new BackgroundPanel(new ImageIcon("images/background.png").getImage());
        setBounds(0, 0, bPanel.getWidth(), bPanel.getHeight());
        DrawJPanel dPanel = new DrawJPanel();
        dPanel.setVisible(true);
        bPanel.add(dPanel);

        //bPanel.add(dPanel);

        //Insets insets = bPanel.getInsets();
        //Dimension size = dPanel.getPreferredSize();

        //dPanel.setBounds(60 + insets.left, 420 + insets.top, size.width, size.height);
        
        bPanel.setVisible(true);
        getContentPane().add(bPanel);

        FileAlterationObserver observer = new FileAlterationObserver("C:\\pictures");
        observer.addListener(new PictureListener());
        FileAlterationMonitor monitor = new FileAlterationMonitor(1, observer);
        try {
            monitor.start();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
